### ISSUE TITLE
choco install mingw-get fails

### ISSUE THREAD

**Issue by alanlivio** [rjocoleman/chocolatey-mingw-get#5]
choco install mingw-get
Chocolatey v0.9.9.5
Installing the following packages:
mingw-get
By installing you accept licenses for the packages.

mingw-get v1.0.2
The package mingw-get wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Do you want to run the script?
 1) yes
 2) no
 3) print
yes
 Get-BinRoot is going to be deprecated by v1. Many packages no longer require it since the folders no longer have versions on them.
 Mode                LastWriteTime     Length Name

---

 d----        05/14/2015     17:41            MinGW

 Extracting 'C:\Users\alan\AppData\Local\Temp\chocolatey\mingw-get\mingw-get-0.6.2-mingw32-beta-20131004-1-bin.tar.xz' to 'C:\bin\MinGW'
 Extracting 'C:\Users\alan\AppData\Local\Temp\chocolatey\mingw-get\mingw-get-0.6.2-mingw32-beta-20131004-1-lic.tar.xz' to 'C:\bin\MinGW'
 Extracting 'C:\Users\alan\AppData\Local\Temp\chocolatey\mingw-get\mingw-get-setup-0.6.2-mingw32-beta-20131004-1-dll.tar.xz' to 'C:\bin\MinGW'
 Extracting 'C:\Users\alan\AppData\Local\Temp\chocolatey\mingw-get\mingw-get-setup-0.6.2-mingw32-beta-20131004-1-xml.tar.xz' to 'C:\bin\MinGW'
 Adding 'C:\bin\MinGW\bin' to the path and the current shell path
 Copy-Item : Cannot find path 'C:\bin\MinGW\var\lib\mingw-get\data\defaults.xml' because it does not exist.
 At C:\ProgramData\chocolatey\lib\mingw-get\tools\chocolateyInstall.ps1:28 char:3
-   Copy-Item "$installDir\var\lib\mingw-get\data\defaults.xml" "$installDir\var\l ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (C:\bin\MinGW\va...ta\defaults.xml:String) [Copy-Item], ItemNotFoundExce
    ption
  - FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
    PATH environment variable does not have C:\bin\MinGW\bin in it. Adding...
    WARNING: Write-ChocolateySuccess is deprecated. If you are the maintainer, please remove it from your package file.
    The install of mingw-get was NOT successful.
    Error while running 'C:\ProgramData\chocolatey\lib\mingw-get\tools\chocolateyInstall.ps1'.
    See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
- mingw-get

**Comment by perlun** [comment]
:+1:, I can reproduce this also. Has the layout of something on the mingw side or elsewhere changed since the `mingw-get` package was created mayhaps?

**Comment by alanlivio** [comment]
Hi @perlun.
There is no mingw-get package in winget.

```powerhell
$ winget search mingw
No package found matching input criteria.
```

**Comment by perlun** [comment]
Thanks @alanlivio. I hardly have any idea idea what this relates to any more. :see_no_evil: Too long ago...

**Comment by alanlivio** [comment]
Hi @perlun. I tried today and the command `choco install mingw-get --force` gets stuck in the 7za.exe call:


![image](https://user-images.githubusercontent.com/604808/154845811-7ed2f4ee-1760-47fa-9e50-7108bb6bf248.png)

**Comment by perlun** [comment]
Hmm, that's bad. How long did you leave it before considering that it had gotten stuck btw, at least a few minutes or so?

**Comment by alanlivio** [comment]
hi @perlun. Just 1 min.

**Comment by perlun** [comment]
OK. Try it again and leave it for at least 5 minutes. 🙂

**Comment by alanlivio** [comment]
Hi. Same thing >5min and choco seem not high memory/processing consuming.

![image](https://user-images.githubusercontent.com/604808/155120018-40984adb-376d-46ce-ad81-f39a2465357e.png)

**Comment by perlun** [comment]
OK, thanks. 👍 Then I really don't know. 😂 Try getting in touch with @rjocoleman somehow to see if he has any ideas or insights.

**Comment by rjocoleman** [comment]
I'm entirely out of this ecosystem sorry all! 

I have no memory of writing this or access to machines that would run it.
I'm going to archive this repo - sorry I can't help more.
